= Quarkus QR Code generator

A small application that generates a QR-Code from text.

== JVM-Mode

=== Application
.Building the application
[source, bash]
----
./mvnw clean package
----

=== Container image
.Build a container image
[source, bash]
----
./mvnw \
  --define build-container-image \
  clean package
----
The resulting image will be named `de.turing85/qr-code-generator:latest`

=== Starting a container and testing the application
.Starting the image
[source, bash]
----
docker run \
  --detach \
  --rm \
  --publish 8080:8080 \
  --name qr-code-generator \
  de.turing85/qr-code-generator:latest
----

To test the application, access link:http://localhost:8080/qr-code/foo%20bar%20baz[]

=== Stopping the container
.Stopping the container
[source, bash]
----
docker stop qr-code-generator
----

== Native mode

=== Application
.Building the application
[source, bash]
----
./mvnw \
  --define native \
  clean package
----

=== Container image
.Build a container image
[source, bash]
----
./mvnw \
  --define native \
  --define build-container-image \
  clean package
----
The resulting image will be named `de.turing85/qr-code-generator:latest` and `de.turing85/qr-code-generator:native`

=== Starting a container and testing the application
.Starting a container
[source, bash]
----
docker run \
  --detach \
  --rm \
  --publish 8080:8080 \
  --name qr-code-generator \
  de.turing85/qr-code-generator:latest
----

To test the application, access link:http://localhost:8080/qr-code/foo%20bar%20baz[]

=== Stopping the container
.Stopping the container
[source, bash]
----
docker stop qr-code-generator
----