name: Populate Cache

description: |
  An action to populate the maven cache.

runs:
  using: composite

  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 17
      id: setup

    - name: Populate Cache
      if: ${{ steps.setup.outputs.cache-hit != 'true' }}
      shell: sh
      run: |
        mvn \
          --batch-mode \
          --define ci-populate-cache \
          verify \
          quarkus:go-offline \
          de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

    - name: Cancel Build
      if: ${{ failure() }}
      uses: andymckay/cancel-action@0.3