name: Populate Cache

description: |
  An action to populate the maven cache.

inputs:
  graalvm-distribution:
    description: The distribution of GraalVM to use
    default: mandrel
    required: true
  graalvm-version:
    description: The version of the GraalVM distribution to use
    default: 22.3.1-Final
    required: true
  java-version:
    description: The Java version to use
    default: '17'
    required: true
  owasp-data-cache:
    description: The name of the owasp data cache.
    default: owasp-data-cache
    required: true

runs:
  using: composite

  steps:
    - name: Set up ${{ inputs.graalvm-distribution }} ${{ inputs.graalvm-version }} (Java ${{ inputs.java-version }})
      id: setup
      uses: graalvm/setup-graalvm@v1
      with:
        cache: 'maven'
        distribution: ${{ inputs.graalvm-distribution }}
        java-version: ${{ inputs.java-version }}
        version: ${{ inputs.graalvm-version }}

    - name: Populate Maven Cache
      if: ${{ steps.setup.outputs.cache-hit != 'true' }}
      shell: sh
      run: |
        ./mvnw \
          --batch-mode \
          --color always \
          --define dataDirectory=${{ github.workspace }}/${{ inputs.owasp-data-cache }} \
          quarkus:go-offline \
          de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

    - name: OWASP cache
      id: owasp-cache
      uses: actions/cache@v4
      with:
        key: ${{ inputs.owasp-data-cache }}
        path: ${{ github.workspace }}/${{ inputs.owasp-data-cache }}

    - name: Populate OWASP data cache
      if: ${{ steps.owasp-cache.outputs.cache-hit != 'true' }}
      shell: sh
      run: |
        ./mvnw \
          --batch-mode \
          --color always \
          --define dataDirectory=${{ github.workspace }}/${{ inputs.owasp-data-cache }} \
          dependency-check:update-only

    - name: Cancel Build
      if: ${{ failure() }}
      uses: andymckay/cancel-action@0.3