name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE.txt'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE.txt'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'

concurrency:
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'turing85/quarkus-qr' }}

permissions:
  actions: write
  checks: write
  pull-requests: write

jobs:
  recreate-comment:
    name: Recreate Comment
    uses: turing85/shared-github-workflows/.github/workflows/recreate-comment.yml@main

  populate-cache:
    name: Populate cache
    uses: turing85/shared-github-workflows/.github/workflows/java-populate-cache.yml@main
    with:
      graalvm-distribution: mandrel
      graalvm-version: mandrel-23.1.2.0-Final
      java-version: 21

      maven-opts: >-
        --batch-mode
        --color always
        --define ci-populate-cache
      maven-targets: >-
        verify
        quarkus:go-offline
        de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

  build:
    name: Build

    needs:
      - populate-cache
      - recreate-comment

    uses: turing85/shared-github-workflows/.github/workflows/java-quarkus-single-module-build.yml@main
    with:
      maven-opts-jvm: >-
        --batch-mode
        --color always
        --define build-container-image
        --define ci
      maven-opts-native: >-
        --batch-mode
        --color always
        --define build-container-image
        --define ci-native-compressed
      maven-targets-jvm: verify
      maven-targets-native: verify

  owasp-scan:
    name: OWASP Scan

    needs:
      - populate-cache
      - recreate-comment

    uses: turing85/shared-github-workflows/.github/workflows/java-owasp-scan.yml@main
    with:
      graalvm-distribution: mandrel
      graalvm-version: mandrel-23.1.2.0-Final
      java-version: 21

      maven-opts: >-
        --batch-mode
        --color always
        --define ci-owasp
      maven-targets: org.owasp:dependency-check-maven:check

    secrets:
      nvd-api-key: ${{ secrets.NVD_API_KEY }}
