name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE.txt'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE.txt'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'

concurrency:
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'turing85/quarkus-qr' }}

permissions:
  actions: write
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build
    uses: turing85/shared-github-workflows/.github/workflows/java-quarkus-single-module-build.yml@main
    with:
      graalvm-distribution: mandrel
      graalvm-version: mandrel-23.1.2.0-Final
      java-version: 21
      maven-opts-jvm: >-
        --batch-mode
        --color always
        --define build-container-image
        --define ci
      maven-opts-native: >-
        --batch-mode
        --color always
        --define build-container-image
        --define ci
        --define native-compressed
      maven-opts-owasp: >-
        --batch-mode
        --color always
        --define ci-owasp
      maven-opts-populate: >-
        --batch-mode
        --color always
        --define ci-populate-cache
      maven-targets-jvm: verify
      maven-targets-native: verify
      maven-targets-owasp: package
      maven-targets-populate: >-
        verify
        quarkus:go-offline
        de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
    secrets:
      nvd-api-key: ${{ secrets.NVD_API_KEY }}