name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '**.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '**.md'
      - '**.adoc'
      - '**.txt'
      - '.all-contributorsrc'

concurrency:
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'turing85/quarkus-qr' }}

env:
  DOCKER_BUILDKIT: 1

permissions:
  actions: write
  checks: write
  pull-requests: write

jobs:
  recreate-comment:
    name: Recreate Comment
    uses: turing85/quarkus-qr/.github/workflows/pr-comment-recreate.yml@feature/test-pipeline-calls

  populate-cache:
    name: Populate Cache
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Populate Cache
        uses: ./.github/actions/populate-cache

  build-and-test-jvm:
    name: Build and Test (JVM)
    runs-on: ubuntu-latest

    needs:
      - populate-cache

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: 17

      - name: Build and Test
        run: |
          mvn \
            --batch-mode \
            --define build-container-image \
            --define ci \
            verify

      - name: Upload Maven State
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: maven-state
          path: '**/target/maven-*'
          retention-days: 2

      - name: Upload Compiled Classes
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: compiled-classes
          path: '**/target/*classes'
          retention-days: 2

      - name: Upload JARs
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: jars
          path: '**/target/*.jar'
          retention-days: 2

      - name: Upload Fast-JAR
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: fast-jar
          path: 'target/quarkus-app'
          retention-days: 2

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: test-report-jvm
          path: '**/target/**/TEST*.xml'
          retention-days: 2

  build-and-test-native:
    name: Build and Test (Native)
    runs-on: ubuntu-latest

    needs:
      - populate-cache

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: 17

      - name: Build and Test
        run: |
          mvn \
            --batch-mode \
            --define build-container-image \
            --define ci \
            --define native \
            verify

      - name: Upload executable
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: executable
          path: 'target/*-runner'
          retention-days: 2

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: test-report-native
          path: '**/target/**/TEST*.xml'
          retention-days: 2

  test-report-jvm:
    name: Test Report (JVM)

    needs:
      - recreate-comment
      - build-and-test-jvm

    uses: turing85/quarkus-qr/.github/workflows/pr-report.yml@feature/test-pipeline-calls
    with:
      artifact-name: test-report-jvm
      report-name: JVM Test
      report-only-summary: true
      report-path: '**/target/**/TEST*.xml'

  test-report-native:
    name: Test Report (Native)

    needs:
      - recreate-comment
      - build-and-test-native

    uses: turing85/quarkus-qr/.github/workflows/pr-report.yml@feature/test-pipeline-calls
    with:
      artifact-name: test-report-native
      report-name: Native Test
      report-only-summary: true
      report-path: '**/target/**/TEST*.xml'

  owasp:
    name: OWASP Scan
    runs-on: ubuntu-latest

    needs:
      - recreate-comment
      - build-and-test-jvm

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: OWASP Scan
        uses: ./.github/actions/owasp-scan