name: Cleanup branch caches after merge
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    name: Cleanup branch caches after merge
    uses: turing85/shared-github-workflows/.github/workflows/cleanup-branch-caches.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
