name: Nightly CVE Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  checks: write
  pull-requests: write

jobs:
  populate-cache:
    name: Populate cache
    uses: turing85/shared-github-workflows/.github/workflows/maven-populate-cache.yml@main
    with:
      graalvm-distribution: mandrel
      graalvm-version: mandrel-23.1.2.0-Final
      java-version: 21

      maven-opts: >-
        --batch-mode
        --color always
        --define ci-populate-cache
      maven-targets: >-
        verify
        quarkus:go-offline
        de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

  nightly-cve-scan:
    name: Nightly CVE Scan

    needs:
      - populate-cache

    uses: turing85/shared-github-workflows/.github/workflows/maven-owasp-scan.yml@main
    with:
      graalvm-distribution: mandrel
      graalvm-version: mandrel-23.1.2.0-Final
      java-version: 21
      maven-opts: >-
        --batch-mode
        --color always
        --define ci-owasp
      maven-targets: org.owasp:dependency-check-maven:check

    secrets:
      nvd-api-key: ${{ secrets.NVD_API_KEY }}
